### ISSUE TITLE
Est ce qu'il y a un moyen d'ajouter des RSS sans avoir un compte utilisateur ?

### ISSUE THREAD

**Issue by thomas-louvigne** [theclimber/Bilboplanet#10]
Et / ou sans demander à l'auteur du blog.

**Comment by theclimber** [comment]
Oui

**Comment by thomas-louvigne** [comment]
merci, je vais mieux regarder alors.

## 

Thomas Luquet
mail : thomas@luquet.net
harder better faster stronger

**Comment by theclimber** [comment]
Ah pardon, en relisant votre question je me rend compte que j'ai répondu un peu trop vite :

En fait la bonne réponse c'est "ça dépend"

Déjà dans le nouveau bilboplanet, il sera possible de créer un utilisateur sans devoir le valider auprès de l'auteur du blog

Ensuite, chaque utilisateur peut ajouter des flux. Cependant, en général l'admin doit passer par derrière pour valider le flux. Mais ceci dépend de la config. Il peut aussi par défaut accepter tous les flux.

Donc voilà, j'espère que ça répond mieux à votre question.

Ceci dit, le comportement que je décris ici correspond à ce qui est possible de faire sur le bilboplanet qui se trouve sur la branche "develop" et qui n'est pas encore releasé officiellement !

**Comment by thomas-louvigne** [comment]
Ok je vais donc prendre la branche en développement.

## 

Thomas Luquet
mail : thomas@luquet.net
harder better faster stronger

2012/11/12 Gregoire de Hemptinne notifications@github.com
