### ISSUE TITLE
Impossible d'ajouter un flux

### ISSUE THREAD

**Issue by nicosomb** [theclimber/Bilboplanet#11]
Je viens de créer mon compte sur le nouveau Bilboplanet. 
À la création d'un flux, voici l'erreur que j'ai eue : 

Fatal error: Uncaught exception 'Exception' with message 'Champ 'pending_id' inconnu dans field list (1054)' in /home/planetlibre/public_html/bilbo2/inc/clearbricks/dblayer/class.mysql.php:105 Stack trace: #0 /home/planetlibre/public_html/bilbo2/inc/clearbricks/dblayer/dblayer.php(311): mysqlConnection->db_query(Resource id #13, 'SELECT MAX(pend...') #1 /home/planetlibre/public_html/bilbo2/user/api/feed_api.php(123): dbLayer->select('SELECT MAX(pend...') #2 /home/planetlibre/public_html/bilbo2/user/api/index.php(64): require_once('/home/planetlib...') #3 {main} thrown in /home/planetlibre/public_html/bilbo2/inc/clearbricks/dblayer/class.mysql.php on line 105

**Comment by theclimber** [comment]
Bonjour,

Je vous conseille de lancer le script de synchronisation de la base de donnée et de ré-essayer ensuite.

Pour lancer ce script. Assurez-vous que vous êtes connecté comme administrateur. Puis lancer la page :
http://votre-site.com/inc/upgrade_db.php

Faites-moi signe si ça n'a pas suffit.

Bien à vous
