### ISSUE TITLE
Utilisation de sqlite lors de l'installation

### ISSUE THREAD

**Issue by Hydraze** [theclimber/Bilboplanet#12]
Hello,
Test effectué sur un repo git à jour . Je viens d'effectuer une procédure d'installation d'un bilboplanet en séléctionnant « sqlite » pour la gestion de la base de donnée. Je précise que j'ai laissé les autres champs vides. Néanmoins après validation, une page d'erreur concernant un problème de connection à mysql apparait et c'est avec effroi que je vois que c'est le moteur mysql qui a été choisi et écrit dans la configuration, logique donc que ça ne marche pas : 

```
define('BP_DBDRIVER','mysql');
```

À noter qu'un regard rapide aux en-têtes envoyés lors de la validation de ma requête m'indique bien 

```
DBDRIVER=sqlite
```

Dans le fichier wizard.php, je ne vois aucune reprise de l'information concernant la base de donnée dans les variables écrites dans le fichier de configuration, sqlite et pgsql ne sont pas supportés ?

**Comment by theclimber** [comment]
Merci pour le retour

Je viens de commiter un petit changement sur la branche develop qui devrait régler le problème :
https://github.com/theclimber/Bilboplanet/commit/93cdd0d186a999f2c1061b4a3d8ec9d1ea7cc308

J'ai pas encore eu le temps de tester. Mais en théorie ça devrait régler le problème.
