### ISSUE TITLE
Problème d'encodage lors de la redirection vers l'article originel

### ISSUE THREAD

**Issue by marienfressinaud** [theclimber/Bilboplanet#14]
Lorsque le lien d'un article contient un "&" la redirection se fait avec la forme "&amp;" ce qui mène vers une page 404 not found. J'ai constaté le problème avec mes articles (http://www.planet-libre.org/index.php?post_id=13631&go=external par exemple).

**Comment by theclimber** [comment]
Merci pour ce retour. En effet, il y a un bug à corriger. Je vais regarder ça de plus près
Je vous tiens au courant

**Comment by theclimber** [comment]
J'ai corrigé le problème pour le planet-libre et j'ai également commité le bugfix sur la branch develop :
https://github.com/theclimber/Bilboplanet/commit/031af2ecdd48fa49b3036873887436de6418a43b

**Comment by marienfressinaud** [comment]
Merci !
