### ISSUE TITLE
Problème lors de la migration 1.0 -> 1.1 RC

### ISSUE THREAD

**Issue by pingax** [theclimber/Bilboplanet#5]
Bonjour, 

Je travaille actuellement sur la migration d'un planet de la version 1.0 vers la 1.1. RC. Je viens de tenter l'import depuis l'admin (fichier .json.gz) et j'obtiens le message d'erreur suivant : 

( ! ) Fatal error: Uncaught exception 'Exception' with message 'Cannot truncate a table referenced in a foreign key constraint (`planet`.`bp_feed`, CONSTRAINT `bp_fk_feed_site` FOREIGN KEY (`site_id`) REFERENCES `planet`.`bp_site` (`site_id`)) (1701)' in /var/www/htdocs/bilboplanet/inc/clearbricks/dblayer/class.mysql.php on line 105
( ! ) Exception: Cannot truncate a table referenced in a foreign key constraint (`planet`.`bp_feed`, CONSTRAINT `bp_fk_feed_site` FOREIGN KEY (`site_id`) REFERENCES `planet`.`bp_site` (`site_id`)) (1701) in /var/www/htdocs/bilboplanet/inc/clearbricks/dblayer/class.mysql.php on line 105

Environnement : 
- PHP 5.3.10
- Serveur Lighttpd 1.4.30
- MySQL : 5.5.18

**Comment by theclimber** [comment]
Bonjour,

Hum, ceci est gênant en effet. Pouvez-vous me décrire en détail l'état
de votre migration?
- Quelle version utilisez vous? La 1.1 RC qui se trouve sur le site du
  Bilboplanet? Ou la version sur github?
- Ensuite, avez vous fait une installation "fraiche" de la nouvelle
  version du bilboplanet avant de faire l'import?

Il y a aussi peut-être quelques informations qui pourront vous aider
ici :
http://wiki.bilboplanet.com/index.php/Migrer_une_ancienne_installation

N'hésitez pas si vous avez encore des questions

Bien à vous
Grégoire

On Wed, 28 Mar 2012 00:40:45 -0700, Anthony Jorion
reply@reply.github.com
wrote:

> Bonjour, 
> 
> Je travaille actuellement sur la migration d'un planet de la version
> 1.0 vers la 1.1. RC. Je viens de tenter l'import depuis l'admin
> (fichier .json.gz) et j'obtiens le message d'erreur suivant :
> 
> ( ! ) Fatal error: Uncaught exception 'Exception' with message
> 'Cannot truncate a table referenced in a foreign key constraint
> (`planet`.`bp_feed`, CONSTRAINT `bp_fk_feed_site` FOREIGN KEY
> (`site_id`) REFERENCES `planet`.`bp_site` (`site_id`)) (1701)' in
> /var/www/htdocs/bilboplanet/inc/clearbricks/dblayer/class.mysql.php on
> line 105
> ( ! ) Exception: Cannot truncate a table referenced in a foreign key
> constraint (`planet`.`bp_feed`, CONSTRAINT `bp_fk_feed_site` FOREIGN
> KEY (`site_id`) REFERENCES `planet`.`bp_site` (`site_id`)) (1701) in
> /var/www/htdocs/bilboplanet/inc/clearbricks/dblayer/class.mysql.php on
> line 105
> 
> Environnement : 
> - PHP 5.3.10
> - Serveur Lighttpd 1.4.30
> - MySQL : 5.5.18
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/theclimber/Bilboplanet/issues/5

## 

## 

Grégoire de Hemptinne
email : greg@theclimber.be
Tel : +32 473 460 790

**Comment by pingax** [comment]
J'utilise la version présente sur le site. J'ai procédé à une installation fraiche de la RC avant de tenter de faire l'import.

**Comment by theclimber** [comment]
Avez-vous des tables vides? Lorsqu'on fait un import, il vide les tables. Apparemment l'erreur viendrait du fait qu'il n'arrive pas à vider les tables pour cause d'une clé référence présente et qui empêche l'action.

Donc vérifiez (dans l'ordre) si :
- La table post est vide
- La table feed est vide
- La table site est vide
  Normalement si vous videz les tables dans cet ordre là, ça devrait régler le problème. Une fois les tables vides (vous pouvez faire ça avec phpmyadmin par exemple) re-tentez l'import. Ca devrait passer.

**Comment by pingax** [comment]
Bonjour,

Je viens de retenter... J'ai regardé dans phpmyadmin, les tables citées sont déjà vides. L'import ne marche toujours pas.

**Comment by pingax** [comment]
Bonjour,

Souci résolu. J'essayais d'importer des données d'une base de données mysql-5.1 vers mysql-5.5... D'où les erreurs.

**Comment by theclimber** [comment]
Ah ok, merci pour le retour...

Je n'aurais pas cru que la version mysql pose problème. Surtout que le format d'import/export étant le json.gz n'est pas dépendant de la version de mysql.

**Comment by pingax** [comment]
Oui étonnant. J'ai essayé de migrer en ayant la même version mysql, sans aucun souci...
